# Matrices en Numpy

Basado en documento de la libreria [Numpy](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html)

Importamos la librería Numpy con nombre "np".

In [1]:
import numpy as np

## Matriz por filas

Para crear un arreglo en forma de matriz de 2 dimensiones (filas y columnas), se realiza así

In [2]:
A = np.array([[1,2,3],[4,5,6]])
print(A, A.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [3]:
A2 = np.asarray([[1,2,3],[4,5,6]])
print(A2, A2.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


# Ampliando la matriz

## Agregando filas a una matriz


Si quiere agregar una nueva fila a una matriz:

In [4]:
b = np.array([[7,8,9]])
# axis=0 - concatena a lo largo de las filas
print(np.concatenate((A, b), axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(np.vstack((A, b)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# axis=0 - concatenate a lo largo de las filas
np.append(A, b, axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Agregando Columnas a una matriz


In [7]:
c = np.array([[7],[8]])
# c = np.array([[7,8]]).T
# axis=0 - concatena a lo largo de las columnas
print(np.concatenate((A, c), axis=1))

[[1 2 3 7]
 [4 5 6 8]]


In [8]:
print(np.hstack((A,c)))

[[1 2 3 7]
 [4 5 6 8]]


In [9]:
# axis=0 - concatena a lo largo de las columnas
print(np.append(A, c, axis=1))

[[1 2 3 7]
 [4 5 6 8]]


# Medidas sobre matrices $R^{N\times N}\rightarrow R$ 



## Determinante

In [10]:
Ac = np.append(A, b, axis=0)
np.linalg.det(Ac)

0.0

## Rango

In [11]:
np.linalg.matrix_rank(Ac)

2

## Norma

In [12]:
np.linalg.norm(Ac)

16.881943016134134

In [13]:
np.sqrt(np.sum(Ac**2))

16.881943016134134

## Traza de una matriz

In [14]:
Ac

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.trace(Ac)

15

# Solucion a sistemas de ecuaciones

Sunpoga que se tiene el siguiente sistemas de ecuaciones: <br>
$x+3y+5z=10,$ <br>
$2x+5y+z=8,$ <br>
$2x+3y+8z=13$.

In [16]:
A = np.array([[1, 3, 5],[2, 5, 1],[2,3,8]])
b = np.array([[10, 8, 13]]).T

In [17]:
x1 = np.linalg.inv(A)@b
print(x1)

[[-0.48]
 [ 1.56]
 [ 1.16]]


In [18]:
x2 = np.linalg.inv(A).dot(b)
print(x2)

[[-0.48]
 [ 1.56]
 [ 1.16]]


In [19]:
x2 = np.linalg.solve(A,b)
print(x2)

[[-0.48]
 [ 1.56]
 [ 1.16]]


# Productos entre matrices

In [20]:
A = np.array([[1, 3, 5],[2, 5, 1],[2,3,8]])
B = np.array([[2, 4, 1],[3, 6, 2],[7,2,5]])

In [21]:
A@B

array([[46, 32, 32],
       [26, 40, 17],
       [69, 42, 48]])

In [22]:
B@A

array([[12, 29, 22],
       [19, 45, 37],
       [21, 46, 77]])

In [23]:
A.dot(B)

array([[46, 32, 32],
       [26, 40, 17],
       [69, 42, 48]])

In [24]:
np.linalg.inv(A).dot(B) #A^(-1)B

array([[ 4.28000000e+00, -2.00000000e+00,  3.64000000e+00],
       [-1.16000000e+00,  2.00000000e+00, -1.08000000e+00],
       [ 2.40000000e-01,  4.16333634e-17,  1.20000000e-01]])

In [25]:
np.linalg.solve(A,B)

array([[ 4.28, -2.  ,  3.64],
       [-1.16,  2.  , -1.08],
       [ 0.24,  0.  ,  0.12]])

# Forma Echelon

Tomada de explicacion en [stackexchange](https://math.stackexchange.com/questions/3073083/how-to-reduce-matrix-into-row-echelon-form-in-python/3073117). Primero definimos una funcion que realiza el proceso de reduccion por filas.

In [26]:
def row_echelon(A):
    """ Retorna la forma de echelon de A """

    # Si la matriz A no tiene filas o columnas,
    # entonces se regresa la misma matriz
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # Si todos los elementos de la primera columna son ceros,
        # se realiza la reduccion de la segunda columna
        B = row_echelon(A[:,1:])
        # y despues agregamos la columnas de ceros
        return np.hstack([A[:,:1], B])

    # Si un elemento diferente de cero no esta en la primera fila
    # intercambiamos filas (pivoteo)
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # dividimos la primera fila por su primer elemento
    A[0] = A[0] / A[0,0]
    # restamos la primera fila a las demas filas
    # multiplicadas por el correspondiente primer elemento
    A[1:] -= A[0] * A[1:,0:1]

    # realizamos la reduccion para la segunda fila y columna en adelante
    B = row_echelon(A[1:,1:])

    # agregamos la primera fila y columna, y devolvemos el valor
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])


In [27]:
A = np.array([[4, 7, 3, 8],
              [8, 3, 8, 7],
              [2, 9, 5, 3]], dtype='float')

row_echelon(A)

array([[ 1.        ,  1.75      ,  0.75      ,  2.        ],
       [ 0.        ,  1.        , -0.18181818,  0.81818182],
       [ 0.        ,  0.        ,  1.        , -1.22222222]])