# Vectores en Numpy

Importamos la librería Numpy con nombre "np".

In [0]:
import numpy as np

## Vector Unidimensional

Para crear un arreglo unidimensional, se emplea el comando array, imprimimos el vector y su forma (dimensiones), asi

In [3]:
x = np.array([1,3,4])
print(x,x.shape)

[1 3 4] (3,)


## Vector con dos dimensiones

Los vectores unidimensionales como su nombre lo dice, solo tienen una dimension, y matemáticamente no son vectores, ya que se necesitaria de la segunda dimension para indicar si es vector columna o fila. En general se asumen que los vectores son columna, y su transpuesto es fila, asi:

\begin{align*}
	\mathbf{x} = \left[ {\begin{array}{*{20}{c}}
{{x_1}}\\
{{x_2}}\\
 \vdots \\
{{x_n}}
\end{array}} \right],\quad \mathbf{x}^{\top} = \left[{\begin{array}{*{20}{c}} {{x_1}} & {{x_2}} & \ldots & {{x_n}}\end{array}} \right]
\end{align*}

In [8]:
xc = np.array([[1],[2],[3]]) #Crear vector columna
xf = np.array([[1,2,3]]) #Crear vector fila
print("Vector Columna: ",xc.shape,"\n",xc,"\n Vector fila: ",xf.shape,"\n",xf)

Vector Columna:  (3, 1) 
 [[1]
 [2]
 [3]] 
 Vector fila:  (1, 3) 
 [[1 2 3]]


Tambien podemos convertir el vector unidimensional en uno columna o fila, usando el método "reshape".

In [9]:
xc2 = x.reshape(x.size,1)
xf2 = x.reshape(1,x.size)
print("Vector Columna: ",xc2.shape,"\n",xc2,"\n Vector fila: ",xf2.shape,"\n",xf2)

Vector Columna:  (3, 1) 
 [[1]
 [2]
 [3]] 
 Vector fila:  (1, 3) 
 [[1 2 3]]


Tambien podemos convertir el vector unidimensional en uno columna o fila, usando el método "newaxis".

In [11]:
xc3 = x[:,np.newaxis]
xf3 = x[np.newaxis,:]
print("Vector Columna: ",xc3.shape,"\n",xc3,"\n Vector fila: ",xf3.shape,"\n",xf3)

Vector Columna:  (3, 1) 
 [[1]
 [3]
 [4]] 
 Vector fila:  (1, 3) 
 [[1 3 4]]


## Normal de un vector

La norma de un vector se calcula como,
$$ ||\mathbf{x}|| = \sqrt{\sum_{i=1}^{n} x_{i}^2}, \quad \mathbf{x} \in \mathbb{R}^n $$

In [13]:
# Usando comandos basicos de NumPy
x = np.random.randn(10,1) # Vector aleatorio de 10 filas y una columna

norma = np.sqrt(np.sum(x**2))
print(norma)

3.7646594504478763


In [14]:
# Usando "norm" de NumPy
print(np.linalg.norm(x))

3.7646594504478763


# Producto interno o punto entre vectores

El producto interno se define

\begin{align}
		\mathbf{x} \cdot \mathbf{y} = \mathbf{x}^{\top}\mathbf{y} = x_{1}y_{1} + x_{2}y_{2} + \ldots + x_{n}y_{n} = \sum\limits_{i = 1}^n {{x_i}{y_i}}
\end{align}

In [15]:
# Usando comandos basicos de NumPy
x = np.random.randn(10,1) # Vector aleatorio de 10 filas y una columna
y = np.random.randn(10,1) # Vector aleatorio de 10 filas y una columna

prodint = np.sum(x*y)
print(prodint)

0.6260067279116048


In [18]:
# Usando "dot" de NumPy
print(np.dot(x.T,y))

[[0.62600673]]


In [19]:
# Usando el producto matricial de NumPy
print(x.T@y)

[[0.62600673]]


## Producto externo o exterior

El producto externo se define como
\begin{align*}
\mathbf{x}\mathbf{y}^{\top} = \left[ {\begin{array}{*{20}{c}}
{{x_{1}y_{1}}}&{{x_{1}y_{2}}}& \cdots &{{x_{1}y_{m}}}\\
{{x_{2}y_{1}}}&{{x_{2}y_{2}}}& \cdots &{{x_{2}y_{m}}}\\
 \vdots & \vdots & \ddots & \vdots \\
{{x_{n}y_{1}}}&{{x_{n}y_{2}}}& \cdots &{{x_{n}y_{m}}}
\end{array}} \right]
\end{align*}

In [20]:
# Usando comandos basicos de NumPy
x = np.random.randn(3,1) # Vector aleatorio de 10 filas y una columna
y = np.random.randn(4,1) # Vector aleatorio de 10 filas y una columna

print(x*y.T)

[[-0.1691291   0.65024273 -0.2267572  -0.07340993]
 [-0.44611884  1.71517221 -0.59812687 -0.19363642]
 [-0.40474751  1.55611382 -0.54265891 -0.17567934]]


In [21]:
# Usando el comando outer de NumPy
print(np.outer(x,y))

[[-0.1691291   0.65024273 -0.2267572  -0.07340993]
 [-0.44611884  1.71517221 -0.59812687 -0.19363642]
 [-0.40474751  1.55611382 -0.54265891 -0.17567934]]


In [22]:
# Usando el producto matricial de NumPy
print(x@y.T)

[[-0.1691291   0.65024273 -0.2267572  -0.07340993]
 [-0.44611884  1.71517221 -0.59812687 -0.19363642]
 [-0.40474751  1.55611382 -0.54265891 -0.17567934]]


## Proyeccion de un vector sobre otro



Proyectar un vector sobre otro nos sirve para conocer cuanto del vector $\mathbf{a}$ hay en la dirección del vector $\mathbf{u}$ (vector unitario)

![](https://mathinsight.org/media/image/image/dot_product_projection_unit_vector.png)

In [26]:
a = np.random.randn(3,1) # Vector aleatorio de 10 filas y una columna
u = np.random.randn(3,1) # Vector aleatorio de 10 filas y una columna

u = u/np.linalg.norm(u) #Volvemos u unitario
au = a.T@u #Valor de a en la direccion de u

auv = au*u #vector en la direccion de u con tamaño de la proyeccion de a

apu = a - auv #Vector ortogonal a u (cateto opuesto)

print(np.linalg.norm(apu)) # Distancia minima entre los vectores a y u

1.4950566038295796


# **Ejercicio:**

Determinar la distancia minima entre el punto (1,2) y la recta con pendiente 1 que pasa por el origen.

![](https://raw.githubusercontent.com/cgl-itm/Optimizacion-ITM/refs/heads/main/notebooks/figuras/PuntoRecta.PNG)

In [ ]:
#Hacer codigo aqui